---
#
# ci/pipeline.yml
#
# Pipeline structure file for a Go Project pipeline
#
# DO NOT MAKE CHANGES TO THIS FILE.  Instead, modify
# ci/settings.yml and override what needs overridden.
# This uses spruce, so you have some options there.
#
# author:  James Hunt <james@niftylogic.com>
# created: 2016-03-30

meta:
  name:     (( param "Please name your pipeline" ))
  release:  (( concat meta.name " Release" ))
  target:   (( param "Please identify the name of the target Concourse CI" ))
  pipeline: (( grab meta.name ))

  git:
    email:  (( param "Please provide the git email for automated commits" ))
    name:   (( param "Please provide the git name for automated commits" ))

  image:
    name: gradle
    tag: jdk14

  aws:
    bucket:      (( concat meta.pipeline "-pipeline" ))
    region_name: us-east-1
    access_key: (( param "Please set your AWS Access Key ID" ))
    secret_key: (( param "Please set your AWS Secret Key ID" ))

  github:
    uri:          (( concat "git@github.com:" meta.github.owner "/" meta.github.repo ))
    owner:        (( param "Please specify the name of the user / organization that owns the Github repository" ))
    repo:         (( param "Please specify the name of the Github repository" ))
    branch:       master
    private_key:  (( param "Please generate an SSH Deployment Key for this repo and specify it here" ))
    access_token: (( param "Please generate a Personal Access Token and specify it here" ))

  slack:
    webhook:       (( param "Please specify your Slack Incoming Webhook Integration URL" ))
    username:      concourse
    icon:          https://cl.ly/2F421Y300u07/concourse-logo-blue-transparent.png
    notification: '(( concat ":sadpanda: " meta.pipeline " build failed!<br>URL-GOES-HERE" ))'
    channel:       (( param "Please specify the channel (#name) or user (@user) to send messages to" ))
    fail_moji:     ":airplane_arriving:"
    success_moji:  ":airplane_departure:"
    upset_moji:    ":sad_panda:"
    fail_url: '(( concat "<" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Concourse Failure! " meta.slack.upset_moji ">" ))'

  url: (( param "What is the URL for the Concourse instance this pipeline is located on?" ))

groups:
  - name: (( grab meta.pipeline ))
    jobs:
      - test
      # - test-pr
      - pre
      - rc
      - shipit
      - major
      - minor
      # - bump-patch

jobs:
  - name: test
    public: true
    serial: true
    plan:
      - do:
        - in_parallel:
          - { get: git, trigger: true }
          - { get: pipeline-tasks }
        - task: test
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: (( grab meta.image.name ))
                tag:        (( grab meta.image.tag ))
            inputs:
              - name: git
              - name: pipeline-tasks
            run:
              path: git/ci/scripts/test
              args: []
        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:    '(( concat meta.slack.fail_url " " meta.pipeline ": test job failed" ))'

  - name: pre
    public: true
    serial: true
    plan:
    - do:
      - get: git
        passed:
        - test
        trigger: true
      - get: version
        trigger: true
      - task: release-notes
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: starkandwayne/concourse
              tag: latest
          run:
            path: sh
            args:
            - -ce
            - |
              cd git
              if [ -f ci/release_notes.md ]; then
                echo "######   RELEASE NOTES   ###############"
                echo
                cat ci/release_notes.md
                echo
                echo "########################################"
                echo
              else
                echo "NO RELEASE NOTES HAVE BEEN WRITTEN"
                echo "You *might* want to do that before"
                echo "hitting (+) on that shipit job..."
                echo
              fi
          inputs:
          - name: git
      on_failure:
        put: notify
        params:
          channel:  (( grab meta.slack.channel ))
          username: (( grab meta.slack.username ))
          icon_url: (( grab meta.slack.icon ))
          message: release candidate job 'pre' failed (which is unusual).
          ok: false

  - name: rc
    public: true
    plan:
      - do:
        - in_parallel:
            - { get: git,     trigger: true,  passed: [pre] }
            - { get: version, trigger: false, params: {pre: rc} }
        - put: version
          params: {file: version/number}
        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:    '(( concat meta.slack.fail_url " " meta.pipeline ": rc job failed" ))'

  # - name: bump-patch
  #   public: true
  #   plan:
  #     - do:
  #       - { get: version, trigger: true, params: { bump: patch, pre: rc }, passed: [shipit] } # bump rc + patch, so that subesquent version bumps can trigger a new bump-patch
  #       - { put: version,                params: { file: version/number} }
  #       on_failure:
  #         put: notify
  #         params:
  #           channel:  (( grab meta.slack.channel ))
  #           username: (( grab meta.slack.username ))
  #           icon_url: (( grab meta.slack.icon ))
  #           text:    '(( concat meta.slack.fail_url " " meta.pipeline ": bump-patch job failed" ))'

  - name: minor
    public: true
    plan:
      - do:
        - { get: version, trigger: false, params: {bump: minor} }
        - { put: version,                 params: {file: version/number} }
        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:    '(( concat meta.slack.fail_url " " meta.pipeline ": minor job failed" ))'

  - name: major
    public: true
    plan:
      - do:
        - { get: version, trigger: false, params: {bump: major} }
        - { put: version,                 params: {file: version/number} }
        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:    '(( concat meta.slack.fail_url " " meta.pipeline ": major job failed" ))'

  - name: shipit
    public: true
    serial: true
    plan:
      - do:
        - name: inputs
          in_parallel:
            - { get: version, passed: [rc], params: {bump: final} }
            - { get: git,     passed: [rc] }
            - { get: pipeline-tasks }
        - name: release
          task: release
          config:
            image_resource:
              type: docker-image
              source:
                repository: (( grab meta.image.name ))
                tag:        (( grab meta.image.tag ))
            platform: linux
            inputs:
              - name: version
              - name: git
              - name: pipeline-tasks
            outputs:
              - name: gh
              - name: pushme
            run:
              path: pipeline-tasks/ci/scripts/shipit
              args: []
            params:
              REPO_ROOT:    git
              VERSION_FROM: version/number
              RELEASE_NAME: (( grab meta.release ))
              RELEASE_ROOT: gh
              REPO_OUT:     pushme
              BRANCH:       (( grab meta.github.branch ))
              GIT_EMAIL:      (( grab meta.git.email ))
              GIT_NAME:       (( grab meta.git.name ))
        - name: version
          put: version
          params: { bump: final }
        - name: git
          put: git
          params:
            rebase: true
            repository: pushme/git
        - name: github
          put: github
          params:
            name:   gh/name
            tag:    gh/tag
            body:   gh/notes.md
            globs: [gh/artifacts/*]
        - name: notify
          in_parallel:
          - put: notify
            params:
              channel:  (( grab meta.slack.channel ))
              username: (( grab meta.slack.username ))
              icon_url: (( grab meta.slack.icon ))
              text_file: notifications/message
        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:    '(( concat meta.slack.fail_url " " meta.pipeline ": shipit job failed" ))'

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: git
    type: git
    source:
      ignore_paths: ["ci/*[^md]"]
      uri:         (( grab meta.github.uri ))
      branch:      (( grab meta.github.branch ))
      private_key: (( grab meta.github.private_key ))

  - name: pipeline-tasks
    type: git
    source:
      paths:       ["ci/scripts/*"]
      uri:         (( grab meta.github.uri ))
      branch:      (( grab meta.github.branch ))
      private_key: (( grab meta.github.private_key ))

  - name: version
    type: semver
    source :
      initial_version: (( grab meta.initial_version ))
      driver: git
      uri:         (( grab meta.github.uri ))
      branch: version
      file: version
      private_key: (( grab meta.github.private_key ))

  - name: notify
    type: slack-notification
    source:
      url: (( grab meta.slack.webhook ))

  - name: github
    type: github-release
    source:
      user:         (( grab meta.github.owner ))
      repository:   (( grab meta.github.repo ))
      access_token: (( grab meta.github.access_token ))
