---
meta:
  name:    spring-cloud-config-server
  target:  snw
  url:     https://pipes.starkandwayne.com

  initial_version: 0.0.1

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  aws:
    access_key: ((cfcommunity.access))
    secret_key: ((cfcommunity.secret))

  github:
    owner:  starkandwayne
    repo:   spring-cloud-config-server
    branch: ci
    private_key:  ((github.private-key))
    access_token: ((github.access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       "#config-server-broker"
